#ifndef BECOMPOSEKIT_BECOMPOSEKIT_H
#define BECOMPOSEKIT_BECOMPOSEKIT_H

#define BECOMPOSEKIT_VERSION_MAJOR 0
#define BECOMPOSEKIT_VERSION_MINOR 1
#define BECOMPOSEKIT_VERSION_PATCH 0

namespace BeComposeKit {

const char* VersionString();

} // namespace BeComposeKit

#endif // BECOMPOSEKIT_BECOMPOSEKIT_H
